################################################# Tradução das Variáveis #################################################
renomear_listagens <- c("id_listagem_zip",
                        "listagem_url",
                        "raspar_id",
                        "ultima raspagem",
                        "nome", 
                        "resumo", 
                        "spaço", 
                        "descrição", 
                        "experiencias_oferecidas", 
                        "visao_geral_do_bairro", 
                        "notas",
                        "transito",
                        "acesso",
                        "interacao",
                        "regras_da_casa",
                        "url_pequena", 
                        "url_media",
                        "url_foto",
                        "foto_url_xl",
                        "id_host",
                        "url_host",
                        "url_name", 
                        "url_nome",
                        "tamanho_do_host", 
                        "localizacao_host",
                        "sobre_host",
                        "tempo_de_resposta_host",
                        "taxa_resposta_host", 
                        "taxa_aceitacao_host",
                        "superhost",
                        "url_pequena_host", 
                        "url_foto_host", 
                        "vizinhanca_host",
                        "contagem_listagem_host",
                        "total_contagem_listagem_host", 
                        "verificacoes_hosts",
                        "pic_perfil_host",
                        "verificar_identidade_host", 
                        "rua", "vizinhanca",
                        "limpeza_da_vizinhanca",
                        "grupo_de_limpeza_da_vizinhanca",
                        "cidade",
                        "estado",
                        "cep",
                        "mercado",
                        "localizacao_inteligente",
                        "pais", 
                        "latitude",
                        "longitude",
                        "localizacao_exata",
                        "tipo_propriedade",
                        "tipo_quarto",
                        "acomodacoes",
                        "banheiros",
                        "quarto_de_dormir", 
                        "camas",
                        "tipo_de_cama",
                        "cortesia", 
                        "pre_quartos", 
                        "preco",
                        "preco_da_semana",
                        "preco_do_mes",
                        "seguranca_do_deposito", 
                        "taxa_de_limpeza",
                        "convidados_inclusos",
                        "pessoas_extras",
                        "minimo_de_noites",
                        "maximo_de_noites",
                        "minimo_minimo_de_noites",
                        "maximo_maximo_de_noites",
                        "minimo_maximo_de_noites",
                        "maximo_minimo_de_noites",
                        "media_ntm_minimo_de_noites",
                        "media_ntm_maximo_de_noites",
                        "registro_atualizado",
                        "tem_disponibilidade",
                        "disponibilidade_30",
                        "disponibilidade_60",
                        "disponibilidade_90",
                        "disponibilidade_365",
                        "ultimo_registro_raspado",
                        "numero_de_avaliacoes", 
                        "ltm_numero_de_avaliacoes",
                        "primeira_avaliacao",
                        "ultima_avaliacao",
                        "pontuacao_de_avaliacao", 
                        "precisao_da_avaliacao", 
                        "revisao_pontuacao_de_limpeza",
                        "pontuacoes_de_limpeza",
                        "rever_pontuacoes_de_comunicacao", 
                        "rever_pontuacoes_de_localizacao",
                        "rever_valores_de_pontuacao",
                        "requer_licenca",
                        "licenca",
                        "nome_da_jurisdicao", 
                        "reserva_instantanea", 
                        "viagem_de_negocios_prontas", 
                        "politica_de_cancelamento",
                        "requer_foto_do_perfil_convidado",
                        "requer_verificacao_de_telefone_do_convidado", 
                        "calcular_contagem_de_lista_de_hosts",
                        "calcular_listagem_de_hosts_contar_casas_inteiras",
                        "calcular_listagem_de_hosts_contar_salas_privadas",
                        "calcular_listagem_de_hosts_contar_salas_compartilhadas",
                        "avaliacoes_por_mes")
colnames(listings_zip) <- renomear_listagens

colnames(calendar_zip) <- c("id", "data", "avaliacao", "preco", "ajuste_do_preco", "minimo_de_noites", "maximo_noites")

nomes_listagens <- c("id_listagem", "nome", "id_host", "nome_host", "grupo_de_vizinhanca", "vizinhanca", "latitude", "longitude",
  "tipo_de_sala", "preco", "minimo_de_noites", "numero_de_avaliacoes", "ultima_avaliacao",
  "avaliacoes_por_mes", "contagem_calculada_de_listagens_de_host", "disponibilidade_365")
colnames(listings) <- nomes_listagens

colnames(reviews_zip) <- c("id_listagem", "id_avaliacao", "data", "id_avaliacao", "nome_avaliacao", "comentarios")

colnames(reviews) <- c("id_listagem", "data")

colnames(neighbourhoods) <- c("grupo_de_vizinhos", "vizinhanca")
